//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFD.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetFD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0b11b73b616f6692eb87402afa4d1fba {
            get {
                object obj = ResourceManager.GetObject("0b11b73b616f6692eb87402afa4d1fba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0c07b4427729fdb2616f971c9c509885 {
            get {
                object obj = ResourceManager.GetObject("0c07b4427729fdb2616f971c9c509885", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0d45af193d165ee2f964b7d378b14980 {
            get {
                object obj = ResourceManager.GetObject("0d45af193d165ee2f964b7d378b14980", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0d45af193d165ee2f964b7d378b149801 {
            get {
                object obj = ResourceManager.GetObject("0d45af193d165ee2f964b7d378b149801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11618dd21a7875004eedeea2e1e4f5d7 {
            get {
                object obj = ResourceManager.GetObject("11618dd21a7875004eedeea2e1e4f5d7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14003589ce694835e7694003410fafe4 {
            get {
                object obj = ResourceManager.GetObject("14003589ce694835e7694003410fafe4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14003589ce694835e7694003410fafe41 {
            get {
                object obj = ResourceManager.GetObject("14003589ce694835e7694003410fafe41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14003589ce694835e7694003410fafe42 {
            get {
                object obj = ResourceManager.GetObject("14003589ce694835e7694003410fafe42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16a57c9ac148d33c0470cf8014e26741 {
            get {
                object obj = ResourceManager.GetObject("16a57c9ac148d33c0470cf8014e26741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1c144c06884659866fd714d6cb06d249 {
            get {
                object obj = ResourceManager.GetObject("1c144c06884659866fd714d6cb06d249", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1d84fed9eaa303231928becc36b8f6ec {
            get {
                object obj = ResourceManager.GetObject("1d84fed9eaa303231928becc36b8f6ec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1e92d47fd73e7485693c14ae333f777d {
            get {
                object obj = ResourceManager.GetObject("1e92d47fd73e7485693c14ae333f777d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1e92d47fd73e7485693c14ae333f777d1 {
            get {
                object obj = ResourceManager.GetObject("1e92d47fd73e7485693c14ae333f777d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1e92d47fd73e7485693c14ae333f777d2 {
            get {
                object obj = ResourceManager.GetObject("1e92d47fd73e7485693c14ae333f777d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2f14d8d4b51e2c7dae9cf49d0cb33dc3 {
            get {
                object obj = ResourceManager.GetObject("2f14d8d4b51e2c7dae9cf49d0cb33dc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2f14d8d4b51e2c7dae9cf49d0cb33dc31 {
            get {
                object obj = ResourceManager.GetObject("2f14d8d4b51e2c7dae9cf49d0cb33dc31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _369693bbe52f85425c74561ba6008896 {
            get {
                object obj = ResourceManager.GetObject("369693bbe52f85425c74561ba6008896", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _369693bbe52f85425c74561ba60088961 {
            get {
                object obj = ResourceManager.GetObject("369693bbe52f85425c74561ba60088961", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a9831 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a9831", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98311 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a983110 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a983110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98312 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98312", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98313 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98313", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98314 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98314", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98315 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98315", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98316 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98316", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98317 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98317", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98318 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98318", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52ddd821d2bbf654deb1c54b057a98319 {
            get {
                object obj = ResourceManager.GetObject("52ddd821d2bbf654deb1c54b057a98319", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _57c0f16e94dd8854a9bd0a349cf3ef5f {
            get {
                object obj = ResourceManager.GetObject("57c0f16e94dd8854a9bd0a349cf3ef5f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5f5b11c6ff019a5500a29bbff9bd122b {
            get {
                object obj = ResourceManager.GetObject("5f5b11c6ff019a5500a29bbff9bd122b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6c023ee9771445cb115e92aef6ed1133 {
            get {
                object obj = ResourceManager.GetObject("6c023ee9771445cb115e92aef6ed1133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _73a7bcf4b5e100d8bfd543960cc04fa2 {
            get {
                object obj = ResourceManager.GetObject("73a7bcf4b5e100d8bfd543960cc04fa2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _77004719210676b7c50c18661a26519a {
            get {
                object obj = ResourceManager.GetObject("77004719210676b7c50c18661a26519a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9d5935331e98963679545319e4bcdf27 {
            get {
                object obj = ResourceManager.GetObject("9d5935331e98963679545319e4bcdf27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b68502eb2edb3953e73a54d765ea8add {
            get {
                object obj = ResourceManager.GetObject("b68502eb2edb3953e73a54d765ea8add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b68502eb2edb3953e73a54d765ea8add1 {
            get {
                object obj = ResourceManager.GetObject("b68502eb2edb3953e73a54d765ea8add1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b899f37380292251b37670cb9465008d {
            get {
                object obj = ResourceManager.GetObject("b899f37380292251b37670cb9465008d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b8ca336341665be56341820244c95790 {
            get {
                object obj = ResourceManager.GetObject("b8ca336341665be56341820244c95790", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bdb86fb881a32f0792b24e1a5a2bf87f {
            get {
                object obj = ResourceManager.GetObject("bdb86fb881a32f0792b24e1a5a2bf87f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bh {
            get {
                object obj = ResourceManager.GetObject("bh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BI {
            get {
                object obj = ResourceManager.GetObject("BI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c {
            get {
                object obj = ResourceManager.GetObject("c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c1 {
            get {
                object obj = ResourceManager.GetObject("c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cy {
            get {
                object obj = ResourceManager.GetObject("cy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d0bfdc033b4c8c131929522297f70c28_1_ {
            get {
                object obj = ResourceManager.GetObject("d0bfdc033b4c8c131929522297f70c28(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d15931bc6727edba1420fe200ddba6a9 {
            get {
                object obj = ResourceManager.GetObject("d15931bc6727edba1420fe200ddba6a9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d15931bc6727edba1420fe200ddba6a91 {
            get {
                object obj = ResourceManager.GetObject("d15931bc6727edba1420fe200ddba6a91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d15931bc6727edba1420fe200ddba6a92 {
            get {
                object obj = ResourceManager.GetObject("d15931bc6727edba1420fe200ddba6a92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d746ace9979632dda8a05ccb860fdbdd {
            get {
                object obj = ResourceManager.GetObject("d746ace9979632dda8a05ccb860fdbdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d746ace9979632dda8a05ccb860fdbdd1 {
            get {
                object obj = ResourceManager.GetObject("d746ace9979632dda8a05ccb860fdbdd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dba3967b5ac524322d68af7b4f0e6663 {
            get {
                object obj = ResourceManager.GetObject("dba3967b5ac524322d68af7b4f0e6663", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doc {
            get {
                object obj = ResourceManager.GetObject("doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doctor1 {
            get {
                object obj = ResourceManager.GetObject("doctor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dy {
            get {
                object obj = ResourceManager.GetObject("dy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e4a2163ebf57272dedf7da0d5cfcabf6 {
            get {
                object obj = ResourceManager.GetObject("e4a2163ebf57272dedf7da0d5cfcabf6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eb93249a242872e550b176218f2d181b {
            get {
                object obj = ResourceManager.GetObject("eb93249a242872e550b176218f2d181b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap entrepot {
            get {
                object obj = ResourceManager.GetObject("entrepot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GG {
            get {
                object obj = ResourceManager.GetObject("GG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap h1 {
            get {
                object obj = ResourceManager.GetObject("h1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Health_medical_care_instagram_post {
            get {
                object obj = ResourceManager.GetObject("Health medical care instagram post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Health_medical_care_instagram_post__1_ {
            get {
                object obj = ResourceManager.GetObject("Health medical care instagram post (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Health_medical_care_instagram_post__1_1 {
            get {
                object obj = ResourceManager.GetObject("Health medical care instagram post (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Health_medical_care_instagram_post__2_ {
            get {
                object obj = ResourceManager.GetObject("Health medical care instagram post (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Health_medical_care_instagram_post__2_1 {
            get {
                object obj = ResourceManager.GetObject("Health medical care instagram post (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Health_medical_care_instagram_post__2_2 {
            get {
                object obj = ResourceManager.GetObject("Health medical care instagram post (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Health_medical_care_instagram_post__2_3 {
            get {
                object obj = ResourceManager.GetObject("Health medical care instagram post (2)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Healthcare_Services__Facebook_Post_ {
            get {
                object obj = ResourceManager.GetObject("Healthcare Services (Facebook Post)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HH {
            get {
                object obj = ResourceManager.GetObject("HH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HI {
            get {
                object obj = ResourceManager.GetObject("HI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HI1 {
            get {
                object obj = ResourceManager.GetObject("HI1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hj {
            get {
                object obj = ResourceManager.GetObject("hj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HOO {
            get {
                object obj = ResourceManager.GetObject("HOO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HOO1 {
            get {
                object obj = ResourceManager.GetObject("HOO1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi {
            get {
                object obj = ResourceManager.GetObject("hopi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi1 {
            get {
                object obj = ResourceManager.GetObject("hopi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi2 {
            get {
                object obj = ResourceManager.GetObject("hopi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi3 {
            get {
                object obj = ResourceManager.GetObject("hopi3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi4 {
            get {
                object obj = ResourceManager.GetObject("hopi4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi5 {
            get {
                object obj = ResourceManager.GetObject("hopi5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi6 {
            get {
                object obj = ResourceManager.GetObject("hopi6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hopi7 {
            get {
                object obj = ResourceManager.GetObject("hopi7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hos {
            get {
                object obj = ResourceManager.GetObject("hos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hp {
            get {
                object obj = ResourceManager.GetObject("hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hp1 {
            get {
                object obj = ResourceManager.GetObject("hp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_processing20211111_8387_1k32pjw {
            get {
                object obj = ResourceManager.GetObject("image_processing20211111-8387-1k32pjw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_processing20211111_8387_1k32pjw1 {
            get {
                object obj = ResourceManager.GetObject("image_processing20211111-8387-1k32pjw1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap international_nurse_day_social_media_template {
            get {
                object obj = ResourceManager.GetObject("international nurse day social media template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap international_nurse_day_social_media_template__1_ {
            get {
                object obj = ResourceManager.GetObject("international nurse day social media template (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap knss {
            get {
                object obj = ResourceManager.GetObject("knss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap knss__1_ {
            get {
                object obj = ResourceManager.GetObject("knss (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimalist_Family_Doctor_Logo__1_ {
            get {
                object obj = ResourceManager.GetObject("Minimalist Family Doctor Logo (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimalist_Family_Doctor_Logo__1_1 {
            get {
                object obj = ResourceManager.GetObject("Minimalist Family Doctor Logo (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimalist_Family_Doctor_Logo__1_2 {
            get {
                object obj = ResourceManager.GetObject("Minimalist Family Doctor Logo (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimalist_Family_Doctor_Logo__2_ {
            get {
                object obj = ResourceManager.GetObject("Minimalist Family Doctor Logo (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimalist_Family_Doctor_Logo__2_1 {
            get {
                object obj = ResourceManager.GetObject("Minimalist Family Doctor Logo (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimalist_Family_Doctor_Logo__2_2 {
            get {
                object obj = ResourceManager.GetObject("Minimalist Family Doctor Logo (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pp {
            get {
                object obj = ResourceManager.GetObject("pp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Service {
            get {
                object obj = ResourceManager.GetObject("Service", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Service__1_ {
            get {
                object obj = ResourceManager.GetObject("Service (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SICK {
            get {
                object obj = ResourceManager.GetObject("SICK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sy {
            get {
                object obj = ResourceManager.GetObject("sy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__1_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__2_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__3_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__3_1 {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__4_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__5_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__5_1 {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (5)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__6_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__7_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__8_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_et_Orange_Dessiné_à_la_main_Science_Cours_Enseignement_Diaporama__9_ {
            get {
                object obj = ResourceManager.GetObject("Vert et Orange Dessiné à la main Science Cours Enseignement Diaporama (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Violet_et_Blanc_Covid_19_Illustration_Personnel_Médical_Instagram_Story {
            get {
                object obj = ResourceManager.GetObject("Violet et Blanc Covid-19 Illustration Personnel Médical Instagram Story", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Violet_et_Blanc_Covid_19_Illustration_Personnel_Médical_Instagram_Story1 {
            get {
                object obj = ResourceManager.GetObject("Violet et Blanc Covid-19 Illustration Personnel Médical Instagram Story1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wa {
            get {
                object obj = ResourceManager.GetObject("wa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap White_Blue_Minimalist_World_Health_Day_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("White Blue Minimalist World Health Day Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap White_Blue_Minimalist_World_Health_Day_Instagram_Post__1_ {
            get {
                object obj = ResourceManager.GetObject("White Blue Minimalist World Health Day Instagram Post (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap World_Health_Day_Vector_Design_For_Banner_or_Background_ {
            get {
                object obj = ResourceManager.GetObject("World Health Day Vector Design For Banner or Background ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap World_Health_Day_Vector_Design_For_Banner_or_Background___2_ {
            get {
                object obj = ResourceManager.GetObject("World Health Day Vector Design For Banner or Background  (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap World_Health_Day_Vector_Design_For_Banner_or_Background_1 {
            get {
                object obj = ResourceManager.GetObject("World Health Day Vector Design For Banner or Background 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
