//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=Youtube16;Integrated Secur" +
            "ity=True")]
        public string Youtube16ConnectionString {
            get {
                return ((string)(this["Youtube16ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=UMS0;Integrated Security=T" +
            "rue")]
        public string UMS0ConnectionString {
            get {
                return ((string)(this["UMS0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=SI0;Integrated Security=Tr" +
            "ue")]
        public string SI0ConnectionString {
            get {
                return ((string)(this["SI0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=NEO0;Integrated Security=T" +
            "rue")]
        public string NEO0ConnectionString {
            get {
                return ((string)(this["NEO0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=MAT0;Integrated Security=T" +
            "rue")]
        public string MAT0ConnectionString {
            get {
                return ((string)(this["MAT0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=GO0;Integrated Security=Tr" +
            "ue")]
        public string GO0ConnectionString {
            get {
                return ((string)(this["GO0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=CH0;Integrated Security=Tr" +
            "ue")]
        public string CH0ConnectionString {
            get {
                return ((string)(this["CH0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=OTR0;Integrated Security=T" +
            "rue")]
        public string OTR0ConnectionString {
            get {
                return ((string)(this["OTR0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=CCI0;Integrated Security=T" +
            "rue")]
        public string CCI0ConnectionString {
            get {
                return ((string)(this["CCI0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=MF0;Integrated Security=Tr" +
            "ue")]
        public string MF0ConnectionString {
            get {
                return ((string)(this["MF0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=MH0;Integrated Security=Tr" +
            "ue")]
        public string MH0ConnectionString {
            get {
                return ((string)(this["MH0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=MédSERVICE;Integrated Secu" +
            "rity=True")]
        public string MédSERVICEConnectionString {
            get {
                return ((string)(this["MédSERVICEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=DIALYSE0;Integrated Securi" +
            "ty=True")]
        public string DIALYSE0ConnectionString {
            get {
                return ((string)(this["DIALYSE0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UTILISA-6T0ALDK\\SQLEXPRESS;Initial Catalog=MM;Integrated Security=Tru" +
            "e")]
        public string MMConnectionString {
            get {
                return ((string)(this["MMConnectionString"]));
            }
        }
    }
}
